version: "3.8"
services:
  raspap:
    container_name: raspap
    image: ghcr.io/raspap/raspap-docker:latest
    #build: .
    privileged: true
    network_mode: host
    #cgroup: host # uncomment when using an ARM device 
    environment:
      - RASPAP_SSID=raspap-webgui
      - RASPAP_SSID_PASS=ChangeMe
      - RASPAP_COUNTRY=GB
      - RASPAP_WEBGUI_USER=admin
      - RASPAP_WEBGUI_PASSWORD=secret
      - RASPAP_WEBGUI_PORT=80
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped